#! /bin/sh

#  ____ ____  ______        ____  __
# | __ ) ___||  _ \ \      / /  \/  |
# |  _ \___ \| |_) \ \ /\ / /| |\/| |
# | |_) |__) |  __/ \ V  V / | |  | |
# |____/____/|_|     \_/\_/  |_|  |_|
#

#############
# autostart #
#############

# exec ~/.screenlayout/default.sh &
# exec ~/.screenlayout/doublescreen.sh &

# pkill sxhkd
# sxhkd &

# pkill pasystray
# pasystray &

# /usr/bin/lxqt-policykit-agent &

# nitrogen --restore & 

# pkill picom
# picom -b &

# pkill dunst
# dunst &

# pkill io.elementary.appcenter
# io.elementary.appcenter -s &

# nm-applet & 

# pkill diodon
# diodon &

# pkill blueman-applet
# blueman-applet &

# ff-theme-util &

xsetroot -cursor_name left_ptr &

# exec ~/.config/polybar/executable_launch.sh &

# steam -silent &

# pkill discord
# discord --start-minimized &


###########
# Monitor #
###########

# bspc monitor -d A S D F G H J 
bspc monitor DP-0 -d 1 2 3 4 5 6
# bspc monitor DP-2 -d 7 8
# bspc monitor HDMI-0 -d 9

bspc config top_padding 23

################
# Window rules #
################


bspc rule -a Nitrogen state=floating
bspc rule -a *:calibre-ebook-viewer state=floating
bspc rule -a Wrapper-2.0 state=floating focus=on
bspc rule -a *:"Friends List" state=floating
bspc rule -a Galculator state=floating

####################
# General Settings #
####################

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false 

bspc config border_width         2
bspc config window_gap           10
# bspc config border_radius        10

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Set the border colors.
bspc config normal_border_color "#7aa2f7"
bspc config active_border_color "#7aa2f7"
bspc config focused_border_color "#ad8ee6"
bspc config presel_feedback_color "#ad8ee6"


# bspc config top_padding 12
# bspc config left_padding 12
# bspc config right_padding 12
# bspc config bottom_padding 12
